### ISSUE TITLE
Where is the file /fsdet/data/

### ISSUE THREAD

**Issue by txy791570042** [MegviiDetection/FSCE#2]
As the title, I can't find the file /fsdet/data... I hope you can update it, thanks.

**Comment by bsun0802** [comment]
Done. 

Close the issue if your problem is solved, thx.

**Comment by txy791570042** [comment]
thank you very much
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MegviiDetection/FSCE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MegviiDetection/FSCE] Where is the file /fsdet/data/ (#2)





 
Done.
 
Close the issue if your problem is solved, thx.

**Comment by chengyu0910** [comment]
> Done.
> 
> Close the issue if your problem is solved, thx.

this version still don't contain fsdet/data, can I use the fsdet/data folder from  FsDet [https://github.com/ucbdrive/few-shot-object-detection](url)?

**Comment by bsun0802** [comment]
Sorry for the inconvenience. The problem will be fixed shortly today. 

And if you want, you can use fsdet/data folder from FsDet, but you might need to debug some import errors.

**Comment by Chauncy-Cai** [comment]
@chengyu0910  We have already uploaded the missing file.
